#!/usr/bin/expect -f

set timeout -1

spawn jdb -attach 8080
expect "main"

send "stop at pl.lodz.p.it.isrp.model.PhilosopherModel:34\r"
expect "main"


send "run\r"
expect "Breakpoint hit:"
expect "thread=Wątek reprezentujący filozofa"
expect "Wątek reprezentujący filozofa"


send "print restsCounter\r"
expect "Wątek reprezentujący filozofa"
send "print mealsCounter\r"
expect "Wątek reprezentujący filozofa"


expect eof